/* eslint-disable @next/next/no-sync-scripts */
// import "./globals.css";
import "../../css/style.css";
import "../../css/css-assets.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, intial-scale=1, max-scale=1"
        />
        {/* <!-- Stylesheets
============================================= --> */}
        <link href="/css/css-assets.css" rel="stylesheet" />
        <link href="/css/style.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,600,600i"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700i,700"
          rel="stylesheet"
        />
        {/* <!-- Favicon
	============================================= --> */}
        <link
          rel="shortcut icon"
          href="images/general-elements/favicon/favicon.png"
        />
        <link
          rel="apple-touch-icon"
          href="images/general-elements/favicon/apple-touch-icon.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="images/general-elements/favicon/apple-touch-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="images/general-elements/favicon/apple-touch-icon-114x114.png"
        />
      </Head>
      <>
        <script src="/js/jquery.js" />
        <script src="/js/jRespond.min.js" />
        <script src="/js/jquery.easing.min.js" />
        <script src="/js/jquery.fitvids.js" />
        <script src="/js/jquery.stellar.js" />
        <script src="/js/owl.carousel.min.js" />
        <script src="/js/jquery.mb.YTPlayer.min.js" />
        <script src="/js/jquery.magnific-popup.min.js" />
        <script src="/js/jquery.validate.min.js" />
        <script src="/js/jquery.ajaxchimp.min.js" />
        <script src="/js/simple-scrollbar.min.js" />
        <script src="/js/functions.js" />
      </>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
